[project]
name = 'Cyber-Interruption-Insurance-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.business-impact-calculator]
path = 'contracts/business-impact-calculator.clar'
clarity_version = 3
epoch = 'latest'

[contracts.cyber-incident-detector]
path = 'contracts/cyber-incident-detector.clar'
clarity_version = 3
epoch = '3.2'

[contracts.downtime-measurement-oracle]
path = 'contracts/downtime-measurement-oracle.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
